title: Marie-Aline Millot
author:
  name: Marie-Aline Millot
  email: mariealinemillot@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Marie-Aline Millot is Head of Design at Weekendesk. She designs product, design systems, talks and communities. Her hobby is riding with her motorbike.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
  - about.md
  - works.md
  - talks.md
  - communities.md
  - contact.md

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  skin: classic

social_links:
  linkedin: mariealine
  twitter: mariealine_
  github:  mariealine
  youtube: UCzFwnlibCLeuX1BGYytgXcA
  speakerdeck: mariealine
  malt: mariealine


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-133299862-1